baseURL = ''
languageCode = 'en-us'
title = 'Timothy Marias'
theme="blowfish"
[author]
  name = "Timothy Marias"
  image = "img/profile.jpg"
  headline = "Software Developer"
  links = [
    { github = "https://github.com/timothyjamesmarias" }
  ]
[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"
