[[main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 10
[[main]]
  pre = 'github'
  url = 'https://github.com/timothyjamesmarias'
  weight = 20
 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10
 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 10
