[[main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 10
[[main]]
  name = 'Projects'
  pageRef = 'posts/projects'
  weight = 20
[[main]]
  pre = 'github'
  url = 'https://github.com/timothyjamesmarias'
  weight = 30
 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10
