
[[main]]
  name = 'Blog'
  pageRef = '/blog'
  weight = 10
[[main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 20
[[main]]
  pre = 'github'
  url = 'https://github.com/timothyjamesmarias'
  weight = 30
